### ISSUE TITLE
[Bug] If the individual videos are small enough but added up are too large discord will fail

### ISSUE THREAD

**Issue by Joshua-Noakes1** [Joshua-Noakes1/accore#70]
```shell
[Clear - Success] Successfully cleared downloads folder.

[Discord - Error] Request entity too large

[Discord - Error] DiscordAPIError[40005]: Request entity too large

    at SequentialHandler.runRequest (/app/node_modules/@discordjs/rest/dist/index.js:659:15)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at async SequentialHandler.queueRequest (/app/node_modules/@discordjs/rest/dist/index.js:458:14)

    at async REST.request (/app/node_modules/@discordjs/rest/dist/index.js:902:22)

    at async InteractionWebhook.send (/app/node_modules/discord.js/src/structures/Webhook.js:209:15)

    at async Object.execute (/app/commands/video.js:515:17)

    at async Client.<anonymous> (/app/app.js:92:13)
```

**Comment by Joshua-Noakes1** [comment]
https://github.com/Joshua-Noakes1/raiden/commit/33fb04fd8e34c7f9043b5d53f7b0bfc87aac4574
